################################################################################
# 1. Packages for reading and processing microarray data                       #
################################################################################
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
if (!requireNamespace("limma", quietly = TRUE))
  install.packages("limma")
suppressPackageStartupMessages(library(limma))
if (!requireNamespace("affycoretools", quietly = TRUE))
    BiocManager::install("affycoretools", update = FALSE)
suppressPackageStartupMessages(library(affycoretools))
if (!requireNamespace("oligo", quietly = TRUE))
    BiocManager::install("oligo", update = FALSE)
suppressPackageStartupMessages(library(oligo))
if (!requireNamespace("oligoClasses", quietly = TRUE))
    BiocManager::install("oligoClasses", update = FALSE)
suppressPackageStartupMessages(library(oligoClasses))
if (!requireNamespace("pd.clariom.d.human", quietly = TRUE))
    BiocManager::install("pd.clariom.d.human", update = FALSE)
suppressPackageStartupMessages(library(pd.clariom.d.human))
if (!requireNamespace("clariomdhumanprobeset.db", quietly = TRUE))
    BiocManager::install("clariomdhumanprobeset.db", update = FALSE)
suppressPackageStartupMessages(library(clariomdhumanprobeset.db))
if (!requireNamespace("clariomdhumantranscriptcluster.db", quietly = TRUE))
    BiocManager::install("clariomdhumantranscriptcluster.db", update = FALSE)
suppressPackageStartupMessages(library(clariomdhumantranscriptcluster.db))
if (!requireNamespace("illuminaHumanv4.db", quietly = TRUE))
    BiocManager::install("illuminaHumanv4.db", update = FALSE)
suppressPackageStartupMessages(library(illuminaHumanv4.db))
if (!requireNamespace("TCGAbiolinks", quietly = TRUE))
  BiocManager::install("TCGAbiolinks", update = FALSE)
suppressPackageStartupMessages(library(TCGAbiolinks))


################################################################################
# 2. Utility packages                                                          #
################################################################################
if (!requireNamespace("openxlsx", quietly = TRUE))
    install.packages("openxlsx")
suppressPackageStartupMessages(library(openxlsx))
if (!requireNamespace("dplyr", quietly = TRUE))
    install.packages("dplyr")
suppressPackageStartupMessages(library(dplyr))
if (!requireNamespace("tibble", quietly = TRUE))
  install.packages("tibble")
suppressPackageStartupMessages(library(tibble))
if (!requireNamespace("plyr", quietly = TRUE)) 
  install.packages("plyr")
suppressPackageStartupMessages(library(plyr))
if (!requireNamespace("tidyr", quietly = TRUE))
  install.packages("tidyr")
suppressPackageStartupMessages(library(tidyr))
if (!requireNamespace("stringr", quietly = TRUE))
  install.packages("stringr")
suppressPackageStartupMessages(library(stringr))
if (!requireNamespace("DBI", quietly = TRUE))
  install.packages("DBI")
suppressPackageStartupMessages(library(DBI))
if (!requireNamespace("MatrixGenerics", quietly = TRUE))
  install.packages("MatrixGenerics")
suppressPackageStartupMessages(library(MatrixGenerics))

################################################################################
# 3. Visualization packages                                                    #
################################################################################
if (!requireNamespace("ggplot2", quietly = TRUE))
    install.packages("ggplot2")
suppressPackageStartupMessages(library(ggplot2))
if (!requireNamespace("ggpubr", quietly = TRUE))
  install.packages("ggpubr")
suppressPackageStartupMessages(library(ggpubr))
if (!requireNamespace("ggbiplot", quietly = TRUE))
    BiocManager::install("ggbiplot", update = FALSE)
suppressPackageStartupMessages(library(ggbiplot))
if (!requireNamespace("ggrepel", quietly = TRUE))
    install.packages("ggrepel")
suppressPackageStartupMessages(library(ggrepel))
if (!requireNamespace("pheatmap", quietly = TRUE))
    install.packages("pheatmap")
suppressPackageStartupMessages(library(pheatmap))
if (!requireNamespace("RColorBrewer", quietly = TRUE))
    install.packages("RColorBrewer")
suppressPackageStartupMessages(library(RColorBrewer))
if (!requireNamespace("reshape2", quietly = TRUE))
    install.packages("reshape2")
suppressPackageStartupMessages(library(reshape2))
if (!requireNamespace("viridis", quietly = TRUE))
    install.packages("viridis")
suppressPackageStartupMessages(library(viridis))
if (!requireNamespace("VennDiagram", quietly = TRUE))
    install.packages("VennDiagram")
suppressPackageStartupMessages(library(VennDiagram))
if (!requireNamespace("GOplot", quietly = TRUE))
    install.packages("GOplot")
suppressPackageStartupMessages(library(GOplot))
if (!requireNamespace("ComplexUpset", quietly = TRUE))
    install.packages("ComplexUpset")
suppressPackageStartupMessages(library(ComplexUpset))
if (!requireNamespace("conicfit", quietly = TRUE))
    install.packages("conicfit")
suppressPackageStartupMessages(library(conicfit))
if (!requireNamespace("scatterpie", quietly = TRUE))
    install.packages("scatterpie")
suppressPackageStartupMessages(library(scatterpie))
if (!requireNamespace("ComplexHeatmap", quietly = TRUE))
    install.packages("ComplexHeatmap")
suppressPackageStartupMessages(library(ComplexHeatmap))
if (!requireNamespace("circlize", quietly = TRUE))
    install.packages("circlize")
suppressPackageStartupMessages(library(circlize))
if (!requireNamespace("gridtext", quietly = TRUE))
    install.packages("gridtext")
suppressPackageStartupMessages(library(gridtext))
if(!requireNamespace("RCy3"))
  BiocManager::install("RCy3", update = FALSE)
suppressPackageStartupMessages(library(RCy3))

################################################################################
# 4. Gene set enrichment and annotation packages                               #
################################################################################
if (!requireNamespace("AnnotationDbi", quietly = TRUE))
    BiocManager::install("AnnotationDbi", update = FALSE)
suppressPackageStartupMessages(library(AnnotationDbi))
if (!requireNamespace("org.Hs.eg.db", quietly = TRUE))
    BiocManager::install("org.Hs.eg.db", update = FALSE)
suppressPackageStartupMessages(library(org.Hs.eg.db))
if (!requireNamespace("clusterProfiler", quietly = TRUE))
    BiocManager::install("clusterProfiler", update = FALSE)
suppressPackageStartupMessages(library(clusterProfiler))
if (!requireNamespace("DOSE", quietly = TRUE))
    BiocManager::install("DOSE", update = FALSE)
suppressPackageStartupMessages(library(DOSE))
if (!requireNamespace("KEGGREST", quietly = TRUE))
    BiocManager::install("KEGGREST", update = FALSE)
suppressPackageStartupMessages(library(KEGGREST))
if (!requireNamespace("msigdbr", quietly = TRUE))
    BiocManager::install("msigdbr", update = FALSE)
suppressPackageStartupMessages(library(msigdbr))
if (!requireNamespace("reactome.db", quietly = TRUE))
    BiocManager::install("reactome.db", update = FALSE)
suppressPackageStartupMessages(library(reactome.db))
if (!requireNamespace("GSVA", quietly = TRUE))
  BiocManager::install("GSVA", update = FALSE)
suppressPackageStartupMessages(library(GSVA))
if (!requireNamespace("rrvgo", quietly = TRUE))
  BiocManager::install("rrvgo", update = FALSE)
suppressPackageStartupMessages(library(rrvgo))
if (!requireNamespace("igraph", quietly = TRUE))
  BiocManager::install("igraph", update = FALSE)
suppressPackageStartupMessages(library(igraph))
if (!requireNamespace("hacksig", quietly = TRUE))
  BiocManager::install("hacksig", update = FALSE)
suppressPackageStartupMessages(library(hacksig))

