name: salmon_index
description: |
  Create index for transcriptome quantification using Salmon (v1.10.1)
keywords:
  - salmon
  - index
  - genome
  - reference
tools:
  - salmon:
      description: Create index for transcriptome quantification using Salmon (v1.10.1)
      homepage: https://salmon.readthedocs.io/en/latest/index.html
      documentation: https://salmon.readthedocs.io/en/latest/salmon.html
      doi: "10.1038/nmeth.4197"
      licence: ["GPL-3.0"]
      identifier: ""
input:
  - genome_fasta:
      type: file
      description: Genome FASTA file (e.g. .fa, .fasta)
      pattern: "*.{fasta,fna,faa,fa,fasta.gz,fna.gz,faa.gz,fa.gz}"
      required: true
  - transcript_fasta:
      type: file
      description: Transcript FASTA file (e.g. .fa, .fasta)
      pattern: "*.{fasta,fna,faa,fa,fasta.gz,fna.gz,faa.gz,fa.gz}"
      required: true
  - args:
      type: string
      description: Additional options for Salmon index creation
      required: false
      default: "--gencode -k 31"
output:
  - index:
    - "*.salmon.idx":
      type: directory
      description: Folder containing the salmon index files
      pattern: "*{.salmon.idx}"
author:
  - "@hmarton98"
maintainer:
  - "@hmarton98"