name: hmmpress
description: prepare an HMM database for faster hmmscan searches using HMMER 3.3.2 (Nov 2020)
keywords:
  - hmmer
  - hmmpress
  - database
  - index
tools:
  - hmmscan:
      description: prepare an HMM database for faster hmmscan searches using HMMER 3.3.2 (Nov 2020)
      homepage: https://hmmer.org
      documentation: http://eddylab.org/software/hmmer/Userguide.pdf
      doi: "10.1371/journal.pcbi.1002195"
      licence: ["BSD"]
      identifier: ""
input:
  - hmm:
      type: file
      description: HMMER database file (e.g. .hmm)
      pattern: "*.{hmm, hmm.gz}"
      required: true
output:
  - output:
    - "*.h3?":
      type: list
      description: Binary files with compressed profiles and their index
      pattern: "*.h3?"
author:
  - "@hmarton98"
maintainer:
  - "@hmarton98"