name: glioblastoma
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - star=2.7.11b
  - seqtk=1.4
  - fastqc=0.12.1
  - trim-galore=0.6.10
  - gffread=0.12.7
  - samtools=1.19.2
  - hisat2=2.2.1
  - salmon=1.10.1
  - star=2.7.11b
  - bedops=2.4.41
  - subread=2.0.6
  - picard=3.1.1
  - multiqc=1.10.1
